version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # Optional: Add environment variables if needed
    # environment:
    #   - NODE_ENV=production
    
    # Optional: Add volume for development (hot reload)
    # volumes:
    #   - ./src:/app/src
    
    # Optional: Add container name
    container_name: angular-client