export enum BrowserType {
  CHROME = "CHROME",
  FIREFOX = "FIREFOX",
  SAFARI = "SAFARI",
  EDGE = "EDGE",
  OPERA = "OPERA",
  SAMSUNG_BROWSER = "SAMSUNG_BROWSER",
  MOBILE_SAFARI = "MOBILE_SAFARI",
  INTERNET_EXPLORER = "INTERNET_EXPLORER",
  UC_BROWSER = "UC_BROWSER",
  UNKNOWN = "UNKNOWN"
}